import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Zenversee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="text-[62.5%] leading-[1.25]">
      <body className={`${inter.className} bg-primary leading-[1]`}>{children}</body>
    </html>
  );
}
